services:

  postgresql:
    container_name: transfer_pgsql
    image: postgres
    environment:
      POSTGRES_USER: transfer
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: transfer_money
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5440:5432"
    networks:
      - transfer-bm
    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: money_transfer_redis_cache
    hostname: localhost
    ports:
      - "6380:6379"
    networks:
      - transfer-bm
    restart: unless-stopped


  zipkin:
    container_name: money_transfer_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - transfer-bm

networks:
  transfer-bm:

volumes:
  postgres: