spring:
  application:
    name: fund-transfer
  # Database Configuration


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://c6sfjnr30ch74e.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d5hi7p2ff12nug
    username: u1sq3qcqrp4u76
    password: p87c0620d9d378d7969cac15eda5efea9c7521303821a39e8124f3f575ea25841
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      eclipselink:
        logging:
          level:
            org:
              hibernate:
                SQL: debug
                type:
                  descriptor: trace
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammadhussein2312@gmail.com
    password: rnnl zoil doya pagh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Redis Config
  data:
    redis:
      host: localhost
      port: 6380
      repositories:
        enabled: false

application:
  security:
    jwt:
      secret-key: 40DKJ2234HKJH34KJ2HKJ2UY23U4234U2Y34H2KJH5KH7K6H7K5KJ32H56KJH46KJ4H57H45K8JHLK45KJHEKHKJH6KJH54KJHTKEJHTKB4532
      expiration: 18000000

server:
  port: ${PORT:5000}

  servlet:
     session:
        timeout: 30m
# Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      accountTransferBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

        max-attempts: 5
        wait-duration: 2s

java:
  runtime:
    version: 17


  ratelimiter:
    instances:
      companyBreaker:
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2

