 create table accounts (
        balance numeric(38,2) not null,
        date_of_birth date not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_modified timestamp(6) not null,
        account_number varchar(255) not null unique,
        country varchar(255) not null check (country in ('EGP','USD','EUR','GBP','SAR')),
        email varchar(255) not null unique,
        password varchar(255) not null,
        user_name varchar(255) not null unique,
        primary key (id)
    )